from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from loguru import logger

from autonomous_workflow_agent.app.ai.openai_client import get_openai_client
from autonomous_workflow_agent.app.config import get_reports_dir
from autonomous_workflow_agent.app.workflows.models import EmailData, ReportData, UrgencyLabel

_SUMMARY_SYSTEM = """\
You are a senior executive assistant producing concise, actionable email briefings.
Write clearly and professionally. No bullet points in the summary — flowing prose only.
Maximum 3 paragraphs."""

_INSIGHTS_SYSTEM = """\
You are a sharp business analyst. Extract the 4 most actionable insights from the email data below.
Return exactly 4 numbered insights, one per line. Be specific and concrete."""


def _urgency_stats(emails: list[EmailData]) -> tuple[dict[str, int], list[str]]:
    stats = {UrgencyLabel.IMPORTANT: 0, UrgencyLabel.REVIEW: 0, UrgencyLabel.LOW: 0}
    priority: list[str] = []
    for email in emails:
        if email.sentiment:
            label = email.sentiment.urgency_label
            stats[label] += 1
            if label == UrgencyLabel.IMPORTANT:
                priority.append(f"**{email.sender}** — {email.subject}")
    return {k.value: v for k, v in stats.items()}, priority


def _format_markdown(report: ReportData) -> str:
    ts = report.generated_at.strftime("%Y-%m-%d %H:%M UTC")
    md = f"# {report.title}\n\n"
    md += f"**Generated:** {ts} · **Model:** {report.model_used} · **Emails:** {report.email_count}\n\n"
    md += "---\n\n## Urgency Breakdown\n\n"
    for label, count in report.urgency_stats.items():
        md += f"- **{label}:** {count}\n"
    if report.priority_emails:
        md += "\n### Priority Action Items\n\n"
        for item in report.priority_emails:
            md += f"- {item}\n"
    md += "\n---\n\n## Summary\n\n"
    md += report.summary + "\n\n---\n\n## Key Insights\n\n"
    for i, insight in enumerate(report.insights, 1):
        md += f"{i}. {insight}\n"
    md += "\n---\n\n*Generated by the Autonomous Workflow Agent — powered by OpenAI gpt-4o-mini.*\n"
    return md


class ReportBuilder:
    """Builds AI-powered reports using OpenAI gpt-4o-mini."""

    def __init__(self) -> None:
        self._client = get_openai_client()

    async def build_report(
        self, emails: list[EmailData], title: str = "Email Intelligence Report"
    ) -> ReportData:
        logger.info(f"Building report for {len(emails)} emails")
        self._client.reset_run_counters()

        urgency_stats, priority_emails = _urgency_stats(emails)

        email_blurbs = "\n---\n".join(
            f"From: {e.sender}\nSubject: {e.subject}\nPreview: {e.snippet[:200]}"
            for e in emails[:10]
        )
        summary_result = await self._client.complete(
            system=_SUMMARY_SYSTEM,
            user=(
                f"Summarise the following {len(emails)} emails in 2-3 professional paragraphs."
                f" Focus on common themes, key senders, and action items.\n\n{email_blurbs}"
            ),
            max_tokens=600,
        )
        summary = summary_result.content.strip() if summary_result.success else "Summary unavailable."

        subjects = "\n".join(f"- {e.subject}" for e in emails[:20])
        senders = "\n".join(f"- {e.sender}" for e in list({e.sender for e in emails[:20]}))
        insights_result = await self._client.complete(
            system=_INSIGHTS_SYSTEM,
            user=f"Email subjects:\n{subjects}\n\nSenders:\n{senders}",
            max_tokens=512,
        )

        raw_insights = insights_result.content if insights_result.success else ""
        insights: list[str] = []
        for line in raw_insights.splitlines():
            clean = line.strip().lstrip("0123456789.-•) ").strip()
            if clean:
                insights.append(clean)
        insights = insights[:4] or ["No actionable insights generated."]

        report = ReportData(
            title=title,
            summary=summary,
            insights=insights,
            urgency_stats=urgency_stats,
            priority_emails=priority_emails,
            email_count=len(emails),
            model_used=self._client._settings.openai_model,
            cached_tokens=0,
        )
        logger.info(f"Report built — {self._client.stats['calls']} OpenAI calls")
        return report

    def save_report(self, report: ReportData, filename: str | None = None) -> Path:
        if not filename:
            ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            filename = f"report_{ts}.md"
        path = get_reports_dir() / filename
        path.write_text(_format_markdown(report), encoding="utf-8")
        logger.info(f"Report saved → {path}")
        return path


def get_report_builder() -> ReportBuilder:
    return ReportBuilder()
